### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by kingsten** [PingPlusPlus/pingpp-js#16]
编译时候出现这个错误：

/root/pingpp-js-master/node_modules/gulp-sourcemaps/node_modules/strip-bom/index.js:2
module.exports = x => {
                    ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/pingpp-js-master/node_modules/gulp-sourcemaps/src/init/index.internals.js:7:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

怎么解决呢？

**Comment by kingstenbanh** [comment]
@kingsten: Are you interested in transferring the `kingsten` username to me? We could work out the terms that are beneficial to you! Please let me know
